/*
 * CDI MLK Interface Agreement
 *
 * CDI MLK Interface Agreement
 *
 * API version: 1.0.0
 * Contact: mikhail.oznobkin@megafon.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func GetPartyId(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
