/*
 * CDI MLK Interface Agreement
 *
 * CDI MLK Interface Agreement
 *
 * API version: 1.0.0
 * Contact: mikhail.oznobkin@megafon.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PartyInfo struct {

	Msisdn string `json:"msisdn"`

	PartyId string `json:"partyId"`
}
