/*
 * Product Catalog View
 *
 * Product Catalog View
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"fmt"
	"log"
	"net/http"

	sw "github.com/moznobkin/MLK-Inteface-Agreements/go"
)

func main() {
	log.Printf("Server started")

	offers, errors := sw.LoadDir("./data/json/")
	for _, offer := range offers {
		sw.ProductOfferings[offer.Id] = offer
	}
	fmt.Printf("Load results: ProductOfferings Loaded - %d, Errors - %d\n", len(offers), len(errors))
	fmt.Print(errors)

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))

}

// func walk() {
// 	err := filepath.Walk(".",
// 		func(path string, info os.FileInfo, err error) error {
// 			if err != nil {
// 				return err
// 			}
// 			fmt.Println(path, info.Size())
// 			return nil
// 		})
// 	if err != nil {
// 		log.Println(err)
// 	}
// }
