/*
 * Product Catalog View
 *
 * Product Catalog View
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"

	sw "github.com/moznobkin/MLK-Inteface-Agreements/go"
)

func main() {
	log.Printf("Server started")
	path, err := os.Executable()
	if err != nil {
		log.Println(err)
	}
	fmt.Println(path)
	walk()
	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}

func walk() {
	err := filepath.Walk(".",
		func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			fmt.Println(path, info.Size())
			return nil
		})
	if err != nil {
		log.Println(err)
	}
}
